# Generated by Django 5.1.5 on 2025-08-10 11:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=150, verbose_name='Prénoms')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=150, verbose_name='Lieu de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('adresse', models.CharField(max_length=150, verbose_name='Adresse')),
                ('niveau', models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(6)], verbose_name='Niveau')),
                ('classe', models.CharField(blank=True, max_length=1, null=True, verbose_name='Classe')),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=150, verbose_name='Prénoms')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], db_index=True, max_length=1, verbose_name='Sexe')),
                ('fonction', models.CharField(max_length=20, verbose_name='Fonction')),
                ('telephone', models.CharField(max_length=10, verbose_name='Téléphone')),
            ],
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('prenoms', models.CharField(max_length=100, verbose_name='Prénoms')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('fonction', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonction')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('telephone', models.CharField(max_length=10, verbose_name='Téléphone')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='administrateur_groups', to='auth.group', verbose_name='Groupes')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='administrateur_permissions', to='auth.permission', verbose_name='Permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmploiTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('jour', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], max_length=16, verbose_name='Jour')),
                ('etat', models.CharField(choices=[('Non effectué', 'Non effectué'), ('Effectué', 'Effectué')], default='Non effectué', max_length=12, verbose_name='État')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djembering_online.eleves', verbose_name='Élève')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djembering_online.professeur', verbose_name='Professeur')),
            ],
        ),
        migrations.CreateModel(
            name='CalculHeures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heures_dues', models.FloatField(default=0, verbose_name='Heures dues')),
                ('heures_faites', models.FloatField(default=0, verbose_name='Heures faites')),
                ('heures_complementaires', models.FloatField(default=0, verbose_name='Heures supplémentaires')),
                ('date_changement', models.DateField(blank=True, null=True, verbose_name='Date du dernier changement')),
                ('emploitemps', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='djembering_online.emploitemps', verbose_name='Emploi du temps')),
            ],
        ),
        migrations.CreateModel(
            name='CongeEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(verbose_name='Motif du congé')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('professeur', models.ForeignKey(limit_choices_to={'sexe': 'F'}, on_delete=django.db.models.deletion.CASCADE, to='djembering_online.professeur', verbose_name='Professeur (Femmes uniquement)')),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.CharField(choices=[('Non justifiée', 'Non justifiée'), ('justifiée', 'justifiée')], default='Non justifiée', max_length=25, verbose_name='Justification')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='djembering_online.eleves')),
                ('emploitemps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emploi', to='djembering_online.emploitemps')),
                ('professeur', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='professeur', to='djembering_online.professeur')),
            ],
        ),
        migrations.AddConstraint(
            model_name='emploitemps',
            constraint=models.UniqueConstraint(fields=('professeur', 'jour', 'heure_debut', 'heure_fin'), name='unique_emploi_temps'),
        ),
    ]
