# Generated by Django 5.1.5 on 2025-08-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djembering_online', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='fonction',
            field=models.CharField(max_length=100, verbose_name='Fonction'),
        ),
    ]
