# Generated by Django 5.0.6 on 2025-11-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djembering_online', '0002_alter_professeur_fonction'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='heure_matiere',
            field=models.FloatField(default=0, verbose_name='Heures de matière'),
        ),
    ]
