# Generated by Django 5.0.6 on 2025-11-26 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djembering_online', '0003_professeur_heure_matiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='heure_matiere',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Heures de matière'),
        ),
    ]
